### ISSUE TITLE
[🐞 BUG]: URL link to the documentation in report view in invalid / showing PAGE NOT FOUND ERROR 

### ISSUE THREAD

**Issue by Tufailahmed-Bargir** [ruxailab/RUXAILAB#387] opened 2024-03-19 12:58 UTC
### Description 📝

There is invalid url link in read-documnets in REPORT section

### Link 🔗

https://retlab-dev.firebaseapp.com/reportview/JxEcQ4lRre3a3ZBSi2rX

### Steps to Reproduce 🔄

1. go the the Tests
2. click on the test you have created
3. scroll down to the REPORTs section
4. click on the read documentation link
5. see the error PAGE NOT FOUND

### Screenshots 📸

https://github.com/ruxailab/RUXAILAB/assets/142114244/eb2a8e5e-430c-4fd9-8fd7-179cc320311d

### Expected Behavior 🤔

the url link must be valid

### Actual Behavior 😱

the URL link is invalid

### Environment 🌍

windows 11
web browser : MS edge.

**Comment by Tufailahmed-Bargir** [comment] 2024-03-19 12:59
please assign this issue to me.

**Comment by Tufailahmed-Bargir** [comment] 2024-03-21 09:38
@jvJUCA, I found this issue in live demo, is it a valid bug report??

**Comment by jvJUCA** [comment] 2024-03-27 14:44
Ok, Assigned!

**Comment by Gaurav-Verma07** [comment] 2024-04-14 08:33
Hi @Tufailahmed-Bargir , any progress on this issue? Please share.

**Comment by KarinePistili** [comment] 2024-04-15 20:04
Closing this issue, as it is a duplicate of https://github.com/ruxailab/RUXAILAB/issues/413

**Closed by KarinePistili** 2024-04-15 20:04 UTC
Labels: Bug
